import type { Metadata } from "next";
import "./globals.css";

import { Toaster } from "react-hot-toast";
import Header from "./Header/page";



export const metadata: Metadata = {
  title: "FullStack-PhoneBook",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <>
        <Toaster position="top-left"/>
        <Header/>
        {children}
        </>
      </body>
    </html>
  );
}
